version: '3'
services:
  fluentnao:
    build: .
    image: fluentnao:dev
    platform: linux/amd64
    ports: ['127.0.0.1:5050:5050']
    environment:
      - NAO_IP=${NAO_IP}
    volumes:
      - .:/fluentnao
      - ./photos:/photos
      - ./video:/video
      - ./audio:/audio
      - ~/.ssh:/root/.ssh:ro
